// Stored all the ENUM used in schema

const PERMISSION = ['ADMIN', 'USER', 'GUEST'];

const DISTRIBUTION_TYPE = ['FIXED_AMOUNT', 'FIXED_PERCENTAGE', 'UNIFORM_AMOUNT', 'UNIFORM_PERCENTAGE', 'NORMAL_AMOUNT', 'NORMAL_PERCENTAGE', 'MARKOV_PERCENTAGE'];
const EVENT_TYPE = ["INCOME", "EXPENSE", "INVEST", "REBALANCE"];
const ASSET_ALLOCATION_TYPE = ["FIXED", "GLIDE"];

const TAX_STATUS = ['NON_RETIREMENT', 'PRE_TAX_RETIREMENT', 'AFTER_TAX_RETIREMENT'];
const FILING_STATUS = ['SINGLE', 'MARRIEDJOINT'];


export { PERMISSION, DISTRIBUTION_TYPE, EVENT_TYPE, ASSET_ALLOCATION_TYPE, TAX_STATUS, FILING_STATUS };