import { test, expect } from '@playwright/test';

test('test Scenario for Charts', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('link', { name: 'Continue as Guest' }).click();
  await page.getByRole('link', { name: 'Create Scenario' }).click();
  await page.getByRole('textbox', { name: 'Scenario Name' }).click();
  await page.getByRole('textbox', { name: 'Scenario Name' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Scenario Name' }).fill('Scenario 1');
  await page.getByRole('spinbutton', { name: 'Financial Goal Specify a non-' }).click();
  await page.getByRole('spinbutton', { name: 'Financial Goal Specify a non-' }).fill('10000');
  await page.locator('#state svg').click();
  await page.locator('.css-19bb58m').click();
  await page.getByRole('combobox', { name: 'State of Residence Select...' }).fill('New ');
  await page.getByRole('option', { name: 'New York' }).click();
  await page.getByRole('radio', { name: 'Single' }).check();
  await page.getByRole('spinbutton', { name: 'Your Birth Year' }).click();
  await page.getByRole('spinbutton', { name: 'Your Birth Year' }).fill('2004');
  await page.getByRole('radio', { name: 'Fixed Value' }).check();
  await page.getByTestId('fixedInput').click();
  await page.getByTestId('fixedInput').fill('90');
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.getByRole('heading', { name: 'Investment Types' })).toBeVisible();
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.getByRole('heading', { name: 'Investments' })).toBeVisible();
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.getByRole('heading', { name: 'Event Series' })).toBeVisible();
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.getByRole('heading', { name: 'Inflation & Contribution' })).toBeVisible();
  await page.getByRole('radio', { name: 'Fixed Percentage' }).check();
  await page.getByTestId('fixedInput').click();
  await page.getByTestId('fixedInput').fill('5');
  await page.getByRole('spinbutton', { name: 'After-Tax Retirement Accounts' }).click();
  await page.getByRole('spinbutton', { name: 'After-Tax Retirement Accounts' }).fill('10000');
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.getByRole('heading', { name: 'Spending Strategy' })).toBeVisible();
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.getByRole('heading', { name: 'Expense Withdrawal Strategy' })).toBeVisible();
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.getByRole('heading', { name: 'Required Minimum Distribution' })).toBeVisible();
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.getByRole('heading', { name: 'Roth Conversion Strategy &' })).toBeVisible();
  await page.getByRole('button', { name: 'Save & Close' }).click();
  await expect(page.getByRole('heading', { name: 'My Scenarios' })).toBeVisible();
});


test('Create Scenario for 1D', async ({ page }) => {
    await page.goto('http://localhost:5173/');
    await page.getByRole('link', { name: 'Continue as Guest' }).click();
    await page.getByRole('link', { name: 'Create Scenario' }).click();
    await page.getByRole('textbox', { name: 'Scenario Name' }).click();
    await page.getByRole('textbox', { name: 'Scenario Name' }).press('ControlOrMeta+a');
    await page.getByRole('textbox', { name: 'Scenario Name' }).fill('Scenario 1');
    await page.getByRole('spinbutton', { name: 'Financial Goal Specify a non-' }).click();
    await page.getByRole('spinbutton', { name: 'Financial Goal Specify a non-' }).fill('10000');
    await page.locator('#state svg').click();
    await page.getByRole('combobox', { name: 'State of Residence 50 results' }).fill('New');
    await page.getByRole('option', { name: 'New York' }).click();
    await page.getByRole('radio', { name: 'Single' }).check();
    await page.getByRole('spinbutton', { name: 'Your Birth Year' }).click();
    await page.getByRole('spinbutton', { name: 'Your Birth Year' }).fill('2004');
    await page.getByRole('radio', { name: 'Fixed Value' }).check();
    await page.getByTestId('fixedInput').click();
    await page.getByTestId('fixedInput').fill('91');
    await expect(page.getByRole('heading', { name: 'Basic Information' })).toBeVisible();
    await page.getByRole('button', { name: 'Next' }).click();
    await page.getByRole('button', { name: 'Add New Investment Type' }).click();
    await page.getByRole('textbox', { name: 'Investment Type Name' }).click();
    await page.getByRole('textbox', { name: 'Investment Type Name' }).fill('Stocks');
    await page.getByRole('textbox', { name: 'Investment Type Name' }).press('Enter');
    await page.getByTestId('distributions-expectedAnnualReturn').getByRole('radio', { name: 'Fixed Value or Percentage' }).check();
    await page.getByTestId('fixedInput').click();
    await page.getByTestId('fixedInput').fill('10');
    await page.getByRole('spinbutton', { name: 'Expense Ratio' }).click();
    await page.getByRole('spinbutton', { name: 'Expense Ratio' }).fill('2');
    await page.getByTestId('distributions-expectedDividendsInterest').getByRole('radio', { name: 'Fixed Value or Percentage' }).check();
    await page.getByTestId('distributions-expectedDividendsInterest').getByTestId('fixedInput').click();
    await page.getByTestId('distributions-expectedDividendsInterest').getByTestId('fixedInput').fill('99');
    await page.getByRole('radio', { name: 'Taxable' }).check();
    await page.getByRole('button', { name: 'Create' }).click();
    await expect(page.getByRole('heading', { name: 'Investment Types' })).toBeVisible();
    await page.getByRole('button', { name: 'Next' }).click();
    await expect(page.getByRole('heading', { name: 'Investments' })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Create/Edit Scenario' })).toBeVisible();
    await page.getByRole('button', { name: 'Add New Investment' }).click();
    await page.getByRole('row', { name: 'Select... Select...' }).locator('svg').first().click();
    await page.getByRole('option', { name: 'Stocks' }).click();
    await page.getByRole('row', { name: 'Stocks Select...' }).getByPlaceholder('$').click();
    await page.getByRole('row', { name: 'Stocks Select...' }).getByPlaceholder('$').fill('1000');
    await page.getByRole('cell', { name: 'Select...' }).locator('svg').click();
    await page.getByRole('option', { name: 'Pre-Tax Retirement' }).click();
    await expect(page.getByRole('heading', { name: 'Investments' })).toBeVisible();
    await page.getByRole('button', { name: 'Next' }).click();
    await expect(page.getByRole('heading', { name: 'Create/Edit Scenario' })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Event Series' })).toBeVisible();
    await page.getByRole('button', { name: 'Add New Event Series' }).click();
    await page.getByRole('textbox', { name: 'Event Series Name' }).click();
    await page.getByRole('textbox', { name: 'Event Series Name' }).fill('Job');
    await page.getByTestId('distributions-startYear').getByRole('radio', { name: 'Fixed Value' }).check();
    await page.getByTestId('fixedInput').click();
    await page.getByTestId('fixedInput').fill('2023');
    await page.getByTestId('distributions-duration').getByRole('radio', { name: 'Fixed Value' }).check();
    await page.getByTestId('distributions-duration').getByTestId('fixedInput').click();
    await page.getByTestId('distributions-duration').getByTestId('fixedInput').fill('30');
    await page.getByRole('radio', { name: 'Income' }).check();
    await page.getByRole('spinbutton', { name: 'Initial Value' }).click();
    await page.getByRole('spinbutton', { name: 'Initial Value' }).fill('120000');
    await page.getByRole('radio', { name: 'Fixed Value or Percentage' }).check();
    await page.getByTestId('distributions-expectedAnnualChange').getByTestId('fixedInput').click();
    await page.getByTestId('distributions-expectedAnnualChange').getByTestId('fixedInput').fill('100');
    await expect(page.getByRole('heading', { name: 'New Event Series' })).toBeVisible();
    await page.getByRole('button', { name: 'Create' }).click();
    await expect(page.getByRole('heading', { name: 'Event Series' })).toBeVisible();
    await page.getByRole('button', { name: 'Next' }).click();
    await expect(page.getByRole('heading', { name: 'Inflation & Contribution' })).toBeVisible();
    await page.getByRole('radio', { name: 'Fixed Percentage' }).check();
    await page.getByTestId('fixedInput').click();
    await page.getByTestId('fixedInput').fill('10');
    await page.getByRole('spinbutton', { name: 'After-Tax Retirement Accounts' }).click();
    await page.getByRole('spinbutton', { name: 'After-Tax Retirement Accounts' }).fill('100');
    await page.getByRole('button', { name: 'Next' }).click();
    await expect(page.getByRole('heading', { name: 'Spending Strategy' })).toBeVisible();
    await page.getByRole('button', { name: 'Next' }).click();
    await expect(page.getByRole('heading', { name: 'Expense Withdrawal Strategy' })).toBeVisible();
    await page.getByRole('button', { name: 'Next' }).click();
    await expect(page.getByRole('heading', { name: 'Create/Edit Scenario' })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Required Minimum Distribution' })).toBeVisible();
    await expect(page.locator('[id="_heading_ucsmd_1"]')).toContainText('Required Minimum Distribution Strategy');
    await page.getByRole('button', { name: 'Next' }).click();
    await expect(page.getByRole('heading', { name: 'Roth Conversion Strategy &' })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Create/Edit Scenario' })).toBeVisible();
    await page.getByRole('button', { name: 'Save & Close' }).click();
    await expect(page.getByRole('heading', { name: 'My Scenarios' })).toBeVisible();
  });