import { test, expect } from '@playwright/test';

test('View Scenario', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('link', { name: 'Continue as Guest' }).click();
  await page.getByRole('link', { name: 'Create Scenario' }).click();
  await page.getByRole('textbox', { name: 'Scenario Name' }).click();
  await page.getByRole('textbox', { name: 'Scenario Name' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Scenario Name' }).fill('Scenario 1');
  await page.getByRole('spinbutton', { name: 'Financial Goal Specify a non-' }).click();
  await page.getByRole('spinbutton', { name: 'Financial Goal Specify a non-' }).fill('5173');
  await page.locator('.css-19bb58m').click();
  await page.getByRole('combobox', { name: 'State of Residence 50 results' }).fill('Was');
  await page.getByRole('option', { name: 'Washington' }).click();
  await page.getByRole('radio', { name: 'Single' }).check();
  await page.getByRole('spinbutton', { name: 'Your Birth Year' }).click();
  await page.getByRole('spinbutton', { name: 'Your Birth Year' }).fill('2000');
  await page.getByRole('radio', { name: 'Fixed Value' }).check();
  await page.getByTestId('fixedInput').click();
  await page.getByTestId('fixedInput').fill('120');
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.locator('[id="_heading_nmd6n_1"]')).toContainText('Investment Types');
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.locator('[id="_heading_nmd6n_1"]')).toContainText('Investments');
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.locator('[id="_heading_nmd6n_1"]')).toContainText('Event Series');
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.locator('[id="_heading_nmd6n_1"]')).toContainText('Inflation & Contribution Limits');
  await page.getByRole('radio', { name: 'Fixed Percentage' }).check();
  await page.getByTestId('fixedInput').click();
  await page.getByTestId('fixedInput').fill('5');
  await page.getByRole('spinbutton', { name: 'After-Tax Retirement Accounts' }).click();
  await page.getByRole('spinbutton', { name: 'After-Tax Retirement Accounts' }).fill('100');
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.locator('[id="_heading_nmd6n_1"]')).toContainText('Spending Strategy');
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.locator('[id="_heading_nmd6n_1"]')).toContainText('Expense Withdrawal Strategy');
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.locator('[id="_heading_nmd6n_1"]')).toContainText('Required Minimum Distribution Strategy');
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.locator('[id="_heading_nmd6n_1"]')).toContainText('Roth Conversion Strategy & Optimizer');
  await page.waitForTimeout(10000);
  await page.getByRole('button', { name: 'Save & Close' }).click({ force: true });
  await expect(page).toHaveURL("http://localhost:5173/Home");
  await page.getByText('My Profile').click();
  await page.getByText('My Scenarios').click();
  await expect(page).toHaveURL("http://localhost:5173/Home");
  await page.getByRole('link', { name: 'Scenario 1 Scenario 1 SINGLE' }).click();
  await page.waitForTimeout(30000);
  await expect(page).toHaveURL("http://localhost:5173/Home");
  await page.getByRole('link').filter({ hasText: /^$/ }).first().click();
  await expect(page.locator('h1')).toContainText('View Scenario');
});