import seedrandom from 'seedrandom';
import mongoose from "mongoose";
import DistributionController from "../../db/controllers/DistributionController.js";
import InvestmentTypeController from "../../db/controllers/InvestmentTypeController.js";
import InvestmentController from "../../db/controllers/InvestmentController.js";
import EventController from "../../db/controllers/EventController.js";
import ScenarioController from "../../db/controllers/ScenarioController.js";
import RMDTableController from "../../db/controllers/RMDTableController.js";
import TaxController from "../../db/controllers/TaxController.js";
import ResultController from "../../db/controllers/ResultController.js";
import SimulationController from "../../db/controllers/SimulationController.js";
export const investmentTypeFactory = new InvestmentTypeController();
export const investmentFactory = new InvestmentController();
export const eventFactory = new EventController();
export const scenarioFactory = new ScenarioController();
export const taxFactory = new TaxController();
export const simulationFactory = new SimulationController();
export const distributionFactory = new DistributionController();
export const resultFactory = new ResultController();
export let invMap = new Map();